name: jupyterhub-tutorial
channels:
  - conda-forge
dependencies:
  - python = 3.6
  - jupyterhub == 0.7.2
  - notebook >= 5.0
  - ipykernel >= 4.3
  - jupyterlab = 0.26
  - pip:
    - oauthenticator
    - dockerspawner
    - netifaces
